"""Description des modifications

Revision ID: 895a22202f9e
Revises: 
Create Date: 2024-10-29 11:31:26.896303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '895a22202f9e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.drop_column('genre')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
